#cloud-config
users:
  - name: jatos
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4B9xgvQdrwNXdfV7PgngqiSeCRlYB17L1mnfOkY0FO0xv79su61/bmXBZ3A/6xbgC+Q/I6gYvQUgABtqd2QBs3q5QFRSvC8pfIFaZEiICpVOam4AAPyGRsiqcfoyHyheJOMUzy6QFcQ6S4XiXccPk0ZtaLlaFWl67/kIJXdEq5hDoPFFzjquE/4bNSOpoekV+gmjO5LYB7DSaE3ZAtJ00DvI5bWGEh8BZBRi+eJ/C188eRwFekK3ot/fR5jv+mOtUbNOIdD+GxJ1IxBj9hq+mG/l3TtKTd+qSVmpjS3M59IhN5Dnof3Vw/cCHcYHFyqePzSp0378gDNcbcPH9gepOowL8YHuZT/rzj+Sg8IOmqXKh8D1pvLIAzTxVy95gSGhBAxadnOJvGJyrX4h15suTRms61S5kgcrWk8cxPc0zpDf6bRvBtqlQMOgFKeIyHJEt/a2XGhnS/HXZ43x+OiLnIJFtUBlTDpMy7vlPEB151NDVWqMYkAOZPmykjDCWN+s= fernandezmoralesj@ELSAMSM-400397
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups:
      - sudo
      - docker
    shell: /bin/bash

groups:
  - docker

write-files:
  - path: /etc/ssh/sshd_config.d/custom.conf
    content: |
      port: 22022
      Protocol 2
      HostKey /etc/ssh/ssh_host_rsa_key
      HostKey /etc/ssh/ssh_host_dsa_key
      HostKey /etc/ssh/ssh_host_ecdsa_key
      HostKey /etc/ssh/ssh_host_ed25519_key
      UsePrivilegeSeparation yes
      KeyRegenerationInterval 3600
      ServerKeyBits 1024
      SyslogFacility AUTH
      LogLevel INFO
      LoginGraceTime 120
      PermitRootLogin no
      StrictModes yes
      RSAAuthentication yes
      PubkeyAuthentication yes
      IgnoreRhosts yes
      RhostsRSAAuthentication no
      HostbasedAuthentication no
      PermitEmptyPasswords no
      ChallengeResponseAuthentication no
      X11Forwarding yes
      X11DisplayOffset 10
      PrintMotd no
      PrintLastLog yes
      TCPKeepAlive yes
      AcceptEnv LANG LC_*
      Subsystem sftp /usr/lib/openssh/sftp-server
      UsePAM yes
      AllowUsers jatos
  - path: /home/jatos/.bashrc
    content: |
      alias vim="vim -p"

package_update: true
package_upgrade: true
packages:
  - git
  - vim-nox
  - zsh
  - net-tools
  - docker.io

runcmd:
  - service ssh restart
  - [sh, -c, "chmod 755 /var/tmp"]
  - git clone git@github.com:juanantoniofm/docker.jatos.git

system_info:
  default_user:
    groups: [docker]
